DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  contrasenia VARCHAR(250) NOT NULL,
  correo VARCHAR(250) NOT NULL,
  nombre VARCHAR(250) NOT NULL,
  edad INTEGER DEFAULT NULL,
  fecha_nacimiento VARCHAR(250) DEFAULT NULL
);